kind: pipeline
type: kubernetes
name: default

pipeline:
#- name: build
#  image: plugins/docker
#  settings:
#    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#    dockerfile: Dockerfile
#    dry_run: true

#- name: test
#  image: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#  commands:
#    - mvn test

#- name: publish
#  image: plugins/docker
#  settings:
#    username:
#      from_secret: harbor_user
#    password:
#      from_secret: harbor_password
#    registry: harbor.internal.ddm.zdatainc.io
#    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#    purgue: true
#    tags: ${DRONE_COMMIT}

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    settings:
      chart: ./charts
      release: test
      values: Tag=${DRONE_BRANCH}
    namespace: drone
#  environment:
#    API_SERVER: https://34.70.80.129
#    KUBERNETES_TOKEN:
#      from_secret: kube_token

#- name: publish-gcr
#  image: plugins/gcr
#  purge: true
#  settings:
#    registry: gcr.io
#    repo: digitaldatamarketplace/cicd-demo
#    tags: latest
#    json_key:
#      from_secret: google_credentials
