kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  purge: true
  commands:
  - sleep 5
  - echo helloo
  - echo world

- name: build and publish
  image: plugins/docker
  purge: true
  settings:
    username:
      from_secret: harbor_user
    password:
      from_secret: harbor_password
    registry:
      from_secret: harbor_registry
    repo: library/cicd-demo
    tags: latest
    dockerfile: Dockerfile

#- name: publish
#  image: plugins/gcr
#  purge: true
#  settings:
#    registry: gcr.io
#    repo: digitaldatamarketplace/cicd-demo
#    tags: latest
#    json_key:
#      from_secret: google_credentials

#- name: deploy_helm
#  image: quay.io/ipedrazas/drone-helm
#  settings:
#    skip_tls_verify: true
#    chart: ./charts
#    release: ${DRONE_BRANCH}
#    namespace: drone
#  namespace: drone
#  environment:
#    API_SERVER: https://10.1.2.135:8443
#    KUBERNETES_TOKEN:
#      from_secret: kube_token
