kind: pipeline
type: kubernetes

steps:
- name: build
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build -t hello-world .
  - docker push hello-world
  environment:
    PASSWORD:
      from_secret: HARBOR_PASSWORD
    USERNAME: admin
