---
kind: pipeline
type: kubernetes

steps:
- name: Build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    HARBOR_USERNAME:
      from_secret: HARBOR_USERNAME
    HARBOR_PASSWORD:
      from_secret: HARBOR_PASSWORD
  commands:
  - sleep 5 # give docker enough time to start
  - docker build -t harbor.internal.ddm.zdatainc.io/library/cicd-demo .
  - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.internal.ddm.zdatainc.io
  - docker push harbor.internal.ddm.zdatainc.io/library/cicd-demo
  
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
---
kind: secret
name: HARBOR_PASSWORD
get:
  path: drone-server-secrets
  name: HARBOR_PASSWORD
---
kind: secret
name: HARBOR_USERNAME
get:
  path: drone-server-secrets
  name: HARBOR_USERNAME
---
kind: secret
name: KUBERNETES_TOKEN
get:
  path: drone-server-secrets
  name: KUBERNETES_TOKEN
---
kind: secret
name: KUBERNETES_STAGE_SERVER
get:
  path: drone-server-secrets
  name: KUBERNETES_STAGE_SERVER
