kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  #- sleep 120
  - echo hello
  - echo world

- name: publish  
  image: plugins/gcr
  settings:
    registry: gcr.io
    repo: digitaldatamarketplace/cicd-demo
    tags: latest
    json_key:
      from_secret: google_credentials
      
#- name: docker  
#  image: plugins/docker
#  settings:
#    repo: test/coco
#    build_args:
#      - TEST=coco
