kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
    tags: ${DRONE_COMMIT}
    dockerfile: Dockerfile
    dry_run: true

- name: test
  image: harbor.internal.ddm.zdatainc.io/library/cicd-demo:${DRONE_COMMIT}
  commands:
    - mvn test

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: harbor_user
    password:
      from_secret: harbor_password
    registry: harbor.internal.ddm.zdatainc.io
    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
    purgue: true
    tags: ${DRONE_COMMIT}

#- name: publish
#  image: plugins/gcr
#  purge: true
#  settings:
#    registry: gcr.io
#    repo: digitaldatamarketplace/cicd-demo
#    tags: latest
#    json_key:
#      from_secret: google_credentials

#- name: deploy
#  image: quay.io/ipedrazas/drone-helm
#  settings:
#    skip_tls_verify: true
#    chart: ./charts
#    release: ${DRONE_BRANCH}
#    namespace: drone
#  namespace: drone
#  environment:
#    API_SERVER: https://10.1.2.135:8443
#    KUBERNETES_TOKEN:
#      from_secret: kube_token
