kind: pipeline
type: kubernetes

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username: admin
    password: 
      from_secret: HARBOR_PASSWORD
    registry: harbor.internal.ddm.zdatainc.io
    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
    insecure: true
---
kind: secret
name: HARBOR_PASSWORD
get:
  path: drone-server-secrets
  name: HARBOR_PASSWORD
