kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  purge: true
  commands:
  - sleep 5
  - echo hello
  - echo world

#- name: publish  
#  image: plugins/gcr
#  purge: true
#  settings:
#    registry: gcr.io
#    repo: digitaldatamarketplace/cicd-demo
#    tags: latest
#    json_key:
#      from_secret: google_credentials

- name: deploy
  image: bitsbeats/drone-helm3
  settings:
    kube_api_server: https://10.1.2.135:8443
    kube_token:
      from_secret: kube_token
    chart: ./charts
    release: myapp-staging
    wait: true
    force: true
    namespace: drone
    kube_skip: true
    kube_skip_tls: true
