kind: pipeline
type: kubernetes

steps:
- name: build
  image: alpine
  commands:
  - echo ${HARBOR_PASSWORD}
  - echo ${PASSWORD}
  environment:
    PASSWORD:
      from_secret: HARBOR_PASSWORD
    USERNAME: admin
