kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  #- sleep 120
  - echo hello
  - echo world

- name: docker  
  image: plugins/docker
  settings:
    repo: test/coco
    build_args:
      - TEST=coco
