kind: pipeline
type: kubernetes
name: default

steps:
#- name: build
#  image: plugins/docker
#  settings:
#    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#    dockerfile: Dockerfile
#    dry_run: true

#- name: test
#  image: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#  commands:
#    - mvn test

#- name: publish
#  image: plugins/docker
#  settings:
#    username:
#      from_secret: harbor_user
#    password:
#      from_secret: harbor_password
#    registry: harbor.internal.ddm.zdatainc.io
#    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
#    purgue: true
#    tags: ${DRONE_COMMIT}

- name: deploy_production
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: ./charts
    release: test
    skip_tls_verify: true
    values: Tag=${DRONE_COMMIT}
    #namespace: drone
    api_server:
      from_secret: prod_api_server
    kubernetes_token:
      from_secret: kube_token

#- name: publish-gcr
#  image: plugins/gcr
#  purge: true
#  settings:
#    registry: gcr.io
#    repo: digitaldatamarketplace/cicd-demo
#    tags: latest
#    json_key:
#      from_secret: google_credentials
