kind: pipeline
type: kubernetes
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: admin
    password: ${PASSWORD}
    registry: harbor.internal.ddm.zdatainc.io
    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
    purgue: true
    tags: cocolizo
  environment:
    PASSWORD:
      from_secret: password

---
kind: secret
name: harbor_password
get:
  path: drone-server-secrets
  name: harbor_password
---
kind: secret
name: password
get:
  path: docker
  name: password
