kind: pipeline
type: kubernetes

steps:
- name: build
  commands:
  - ${HARBOR_PASSWORD}
  - ${PASSWORD}
  - docker login -u $USERNAME -p ${HARBOR_PASSWORD} harbor.internal.ddm.zdatainc.io
  - docker build -t harbor.internal.ddm.zdatainc.io/library/hello-world .
  - docker push harbor.internal.ddm.zdatainc.io/library/hello-world
  environment:
    PASSWORD:
      from_secret: HARBOR_PASSWORD
    USERNAME: admin
