kind: pipeline
type: kubernetes
name: default

steps:
- name: deploy_production
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: ./charts
    release: test
    skip_tls_verify: true
    values: Tag=${DRONE_COMMIT}
    namespace: drone
    wait_for_upgrade: true
    cleanup_failed_upgrade: true
    api_server:
      from_secret: prod_api_server
    kubernetes_token:
      from_secret: kubernetes_token
