kind: pipeline
type: kubernetes
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username: admin
    password:
      from_secret: harbor_password
    registry: harbor.internal.ddm.zdatainc.io
    repo: harbor.internal.ddm.zdatainc.io/library/cicd-demo
    purgue: true
    tags: cocolizo
  environment:
    harbor_password:
      from_secret: harbor_password

---
kind: secret
name: harbor_password
get:
  path: drone-server-secrets
  name: harbor_password
