kind: pipeline
type: kubernetes
name: default

steps:
- name: deploy_production
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    chart: ./charts
    release: test
    skip_tls_verify: true
    values: Tag=${DRONE_COMMIT}
    namespace: drone
    wait_for_upgrade: true
    cleanup_failed_upgrade: true
    environment:
      KUBE_API_SERVER: https://34.70.80.129
      KUBE_TOKEN:
        from_secret: kubernetes_token
